version: "3.9"

services:
  db:
    image: postgres:15
    container_name: kupikod_db
    environment:
      POSTGRES_DB: kupikod
      POSTGRES_USER: kupikod
      POSTGRES_PASSWORD: kupikod
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: kupikod_redis
    ports:
      - "6379:6379"

  api:
    build: .
    container_name: kupikod_api
    environment:
      DATABASE_URL: postgresql+psycopg2://kupikod:kupikod@db:5432/kupikod
      VK_TOKEN: ${VK_TOKEN}
      CELERY_BROKER_URL: redis://redis:6379/0
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"

  worker:
    build: .
    container_name: kupikod_worker
    command: celery -A app.tasks.celery_app worker -l info
    environment:
      DATABASE_URL: postgresql+psycopg2://kupikod:kupikod@db:5432/kupikod
      VK_TOKEN: ${VK_TOKEN}
      CELERY_BROKER_URL: redis://redis:6379/0
    depends_on:
      - db
      - redis

volumes:
  db_data:
